name: markdown_quill
description: Convert between quill (delta) format and markdown
version: 1.0.1
repository: https://github.com/TarekkMA/markdown_quill

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  charcode: ^1.3.1
  collection: ^1.18.0
  flutter_quill: ^9.2.10
  markdown: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  meta: ^1.9.1
  very_good_analysis: ^5.1.0
